### PR TITLE
Fix ARIA tablist and ARIA tab scope

### LINKED ISSUE #204: ARIA tablist fails ariaRoleNotScoped audit
`tablist` is not required to be contained within any other ARIA role but this test fails:

```javascript
test('Scope role present - tablist', function() {
    var rule = axs.AuditRules.getRule('ariaRoleNotScoped');
    var fixture = document.getElementById('qunit-fixture');
    var container = fixture.appendChild(document.createElement('ul'));
    container.setAttribute('role', 'tablist');
    for (var i = 0; i < 4; i++) {
        var item = container.appendChild(document.createElement('li'));
        item.setAttribute('role', 'tab');
    }

    var actual = rule.run({ scope: fixture });
    equal(actual.result, axs.constants.AuditResult.PASS);
    deepEqual(actual.elements, []);
});
```

### PR DESCRIPTION
**Pull request by RickSBrown**
Closes #204 
The required context role for `tab` ended up on `tablist` instead.

This motivates me to get onto #105

### CODE REVIEW

**Comment by RickSBrown** [comment]
@alice PTAL

File: test/audits/aria-role-not-scoped-test.js [hunk 1]
```diff
@@ -79,3 +79,33 @@ test('Scope role missing', function() {
...
+    equal(actual.result, axs.constants.AuditResult.PASS);
+    deepEqual(actual.elements, []);
+});
+
+test('Scope role missing - tab', function() {
+    var rule = axs.AuditRules.getRule('ariaRoleNotScoped');
+    var fixture = document.getElementById('qunit-fixture');
+    var expected = [];
+    for (var i = 0; i < 4; i++) {
+        var item = fixture.appendChild(document.createElement('span'));
```
Comment (alice) [inline test/audits/aria-role-not-scoped-test.js]: Why does this test use `span`s where the previous uses a list? Would this test pass if a list was used?

**Comment by alice** [comment]
:+1: modulo test weirdness

File: test/audits/aria-role-not-scoped-test.js (hunk 1 above)
Comment (RickSBrown) [inline test/audits/aria-role-not-scoped-test.js]: It was just to save one line - this test doesn't need a container, the spans are added directly to the fixture. It didn't feel right to add a bunch of `li` elements without a `ul` or `ol`.

I can change it to list if you prefer - the test will still work.

Comment (alice) [inline test/audits/aria-role-not-scoped-test.js]: If you can be bothered, I think it would help avoid future confusion, but :+1: either way.

Comment (RickSBrown) [inline test/audits/aria-role-not-scoped-test.js]: Ok no problem - will make that change then merge it.
