### PR TITLE
Check for any text alternatives when assessing unlabeled images

### LINKED ISSUE #154: ImageWithoutAltText rule should not fail for images with different text alternatives
e.g. `aria-label` or `aria-labelledby`.

### PR DESCRIPTION
**Pull request by alice**
Fixes #154

@ckundo or @RickSBrown PTAL

### CODE REVIEW

File: src/audits/ImageWithoutAltText.js [hunk 1]
```diff
@@ -27,7 +28,16 @@ axs.AuditRules.addRule({
             !axs.utils.isElementOrAncestorHidden(element);
     },
     test: function(image) {
-        return (!image.hasAttribute('alt') && image.getAttribute('role') != 'presentation');
+        var imageIsPresentational = (image.hasAttribute('alt') && image.alt == "") || image.getAttribute('role') == 'presentation';
```
Comment (RickSBrown) [inline src/audits/ImageWithoutAltText.js]: total nit, question of consistency - since the strings are all single quoted should the empty string test be against `''` instead of `""`?

File: test/index.html [hunk 2]
```diff
@@ -56,6 +56,7 @@
     <script src="./audits/bad-aria-attribute-value-test.js"></script>
     <script src="./audits/controls-without-label-test.js"></script>
     <script src="./audits/duplicate-id-test.js"></script>
+    <script src="./audits/image-without-alt-text-test.js"></script>
```
Comment (RickSBrown) [inline test/index.html]: Did you forget to add this test to source control or am I just tired?

File: src/audits/ImageWithoutAltText.js [hunk 3]
```diff
@@ -27,7 +28,16 @@ axs.AuditRules.addRule({
...
+        if (imageIsPresentational)
+            return false;
+        var textAlternatives = axs.properties.getTextProperties(image);
+        if (!textAlternatives)
+            return true;
+        // filename is only present if no other option found
```
Comment (ckundo) [inline src/audits/ImageWithoutAltText.js]: Is this comment necessary? I'm not really sure what it means, and I'm guessing it's ok to remove it for the sake of tidiness.

File: src/audits/ImageWithoutAltText.js [hunk 4]
```diff
@@ -27,7 +28,16 @@ axs.AuditRules.addRule({
...
+        if ('filename' in textAlternatives)
```
Comment (ckundo) [inline src/audits/ImageWithoutAltText.js]: I'm assuming this is checking if the alt text is the same as the filename.

**Comment by ckundo** [comment]
Seems like this PR is missing tests.

File: src/audits/ImageWithoutAltText.js (hunk 1 above)
Comment (alice) [inline src/audits/ImageWithoutAltText.js]: Fixed (nits welcome!)

File: test/index.html (hunk 2 above)
Comment (alice) [inline test/index.html]: Haha, I was tired and forgot to add it. Fixed.

File: src/audits/ImageWithoutAltText.js (hunk 3 above)
Comment (alice) [inline src/audits/ImageWithoutAltText.js]: It was explaining the "why" for the following line, but I've since cleaned up the logic so it's no longer necessary.

File: src/audits/ImageWithoutAltText.js (hunk 4 above)
Comment (alice) [inline src/audits/ImageWithoutAltText.js]: No - the comment explains what this was doing, but the logic has changed now anyway.

**Comment by alice** [comment]
@ckundo @RickSBrown PTAL!

File: src/audits/ImageWithoutAltText.js [hunk 5]
```diff
@@ -27,7 +28,15 @@ axs.AuditRules.addRule({
             !axs.utils.isElementOrAncestorHidden(element);
     },
     test: function(image) {
-        return (!image.hasAttribute('alt') && image.getAttribute('role') != 'presentation');
+        var imageIsPresentational = (image.hasAttribute('alt') && image.alt == '') || image.getAttribute('role') == 'presentation';
```
Comment (ckundo) [inline src/audits/ImageWithoutAltText.js]: Do we care about strict equality here? I noticed you're using it below.

File: src/js/Properties.js [hunk 6]
```diff
@@ -494,31 +494,16 @@ axs.properties.getTextFromHostLanguageAttributes = function(element,
...
+    if (axs.browserUtils.matchSelector(element, 'img') && element.hasAttribute('alt')) {
+        var altValue = {};
+        altValue.type = 'string';
+        altValue.valid = true;
+        altValue.text = element.getAttribute('alt');
+        if (computedName)
+            altValue.unused = true;
+        else
+            computedName = altValue.text;
+        textAlternatives['alt'] = altValue;
```
Comment (ckundo) [inline src/js/Properties.js]: Are we ok mixing dot notation with bracket notation for assignment? We're using both in this block of code.

**Comment by ckundo** [comment]
A few style questions, no blockers though. LGTM!

File: src/audits/ImageWithoutAltText.js [hunk 7]
```diff
@@ -27,7 +28,15 @@ axs.AuditRules.addRule({
...
+        if (imageIsPresentational)
+            return false;
```
Comment (RickSBrown) [inline src/audits/ImageWithoutAltText.js]: Question - should this be in the matcher? In other words should presentational images show a "Pass" (yes it has text alternative) or "NA" (not relevant to this test)?

File: test/audits/image-without-alt-text-test.js [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+    var rule = axs.AuditRules.getRule('imagesWithoutAltText');
+
+    test('Image with no text alternative', function() {
+        var fixture = document.getElementById('qunit-fixture');
+        var img = fixture.appendChild(document.createElement('img'));
+        img.src = 'smile.jpg';
+        var expected = { elements: [img], result: axs.constants.AuditResult.FAIL };
+        deepEqual(rule.run({ scope: fixture }), expected, 'Image has no text alternative');
+    });
+
```
Comment (RickSBrown) [inline test/audits/image-without-alt-text-test.js]: I think two more are needed for completeness to check that presentational images are handled. One with null alt text and one with role presentation.

**Comment by RickSBrown** [comment]
Likewise I see no blockers. It is a nice enhancement.
LGTM @alice

File: src/audits/ImageWithoutAltText.js (hunk 7 above)
Comment (alice) [inline src/audits/ImageWithoutAltText.js]: Good question. I don't think so - I think it makes sense for the scope to be "images", and role=presentation being one technique to make the rule pass. I'll tweak the text to refer to that.

File: src/audits/ImageWithoutAltText.js (hunk 5 above)
Comment (alice) [inline src/audits/ImageWithoutAltText.js]: Good point - we probably don't care here since it'll do the right thing with or without strict equality. It's not really necessary below either.

File: src/js/Properties.js (hunk 6 above)
Comment (alice) [inline src/js/Properties.js]: Heh - that's an interesting question. Ideally we should use bracket notation for anything which is part of the implicit API, but since we're not doing that consistently, it doesn't really matter. Since this hasn't changed in this CL (just the indentation), I'll leave it for now, but we could consider revisiting the dot/bracket inconsistency at some point if we want to do some clean-up.

Comment (ckundo) [inline src/js/Properties.js]: Sounds good.

File: test/audits/image-without-alt-text-test.js (hunk 8 above)
Comment (alice) [inline test/audits/image-without-alt-text-test.js]: Good idea, done.
