### PR TITLE
handle nodes hosted in a <template>

### LINKED ISSUE #337: hasDirectTextDescendantTreeWalker fails when encountering a DocumentFragment in IE11
https://github.com/GoogleChrome/accessibility-developer-tools/blob/master/src/js/Properties.js#L178

`hasDirectTextDescendantTreeWalker` assumes the `parentNode` will have `tagName` defined, but that's not the case for DocumentFragments.

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Fixes #337.
@alice FYI

### CODE REVIEW

File: src/js/Properties.js [hunk 1]
```diff
@@ -175,7 +175,8 @@ axs.properties.hasDirectTextDescendant = function(element) {
         while (treeWalker.nextNode()) {
             var resultElement = treeWalker.currentNode;
             var parent = resultElement.parentNode;
-            var tagName = parent.tagName.toLowerCase();
+            // parent might not be an Element (e.g. DocumentFragment).
+            var tagName = (parent.tagName || '').toLowerCase();
```
Comment (alice) [inline src/js/Properties.js]: Would it make sense to just switch to parentElement on the previous line?

**Comment by valdrinkoshi** [comment]
@alice I've realized the issue happens only if a node is hosted in a <template>, because if we use a DocumentFragment to host nodes and then add the fragment to the main document, the parent of each node will be the new parent, not the DocumentFragment.
This is not the case for <template>:
```js
var frag = document.createDocumentFragment();
frag.appendChild(document.createElement('div'));
document.body.appendChild(frag); // the <div>.parentNode is <body>

var templ = document.createElement('template');
templ.content.appendChild(document.createElement('div'));
document.body.appendChild(templ); // the <div>.parentNode is <template>.content!
```

I've updated the test and the implementation to handle specifically <template>, PTAL 🍰

**Comment by addyosmani** [comment]
LGTM2
