### PR TITLE
Fixes #269, plus a little cleanup from #267

### LINKED ISSUE #269: Exception thrown when testing tooltips without aria-describedby
This line of code (`axs_testing.js:2169`, if that helps) throws an exception
```
return 0 === axs.utils.getAriaIdReferrers(a, "aria-describedby").length;
```
because `axs.utils.getAriaIdReferrers(a, "aria-describedby")` is `null`

### PR DESCRIPTION
**Pull request by alice**

### CODE REVIEW

**Comment by alice** [comment]
@notwaldorf Wanna take a look at this?

File: src/audits/RoleTooltipRequiresDescribedBy.js [hunk 1]
```diff
@@ -30,7 +30,8 @@ axs.AuditRules.addRule({
             !axs.utils.isElementOrAncestorHidden(element);
     },
     test: function(element) {
-        return axs.utils.getAriaIdReferrers(element, 'aria-describedby').length === 0;
+        var referrers = axs.utils.getAriaIdReferrers(element, 'aria-describedby');
+        return !referrers || referrers.length === 0;
```
Comment (notwaldorf) [inline src/audits/RoleTooltipRequiresDescribedBy.js]: 👍

**Comment by notwaldorf** [comment]
LGTM! Thanks so much! :shipit:
