### PR TITLE
Disabled elements should be ignored by low contrast audit

### LINKED ISSUE #205: Disabled button fails the contrast ratio test - should it?
The default contrast ratio of disabled buttons (in Chrome and probably others) fails the low contrast tests.

I would argue that since the user does not / cannot interact with disabled elements they should be ignored for this (and perhaps other?) tests.

Another argument in favor of ignoring them is that if you style a disabled element to meet the contrast ratio audit then it will probably lose the `disabled` look and harm usability.

### PR DESCRIPTION
**Pull request by RickSBrown**
Closes #205 
@alice PTAL

### CODE REVIEW

File: src/js/AccessibilityUtils.js [hunk 1]
```diff
@@ -577,6 +577,40 @@ axs.utils.hasLabel = function(element) {
...
 
 /**
+ * Determine if this element is disabled without considering the effect of a disabled ancestor.
+ * Disabled here means that the element should be considered disabled according to specification.
+ * This element may or may not be effectively disabled in practice as this is dependent on implementation.
+ * @param {Element} element An element to check.
+ * @return {boolean} True if the element is disabled.
+ */
+axs.utils.isElementDisabled = function(element) {
+    if(!element || element.nodeType !== Node.ELEMENT_NODE) {
```
Comment (alice) [inline src/js/AccessibilityUtils.js]: Given that this is being explicitly called with an `Element` object, we probably don't need to check `nodeType`.

File: src/js/AccessibilityUtils.js [hunk 2]
```diff
@@ -577,6 +577,40 @@ axs.utils.hasLabel = function(element) {
...
+ * @return {boolean} True if the element or one of its ancestors is disabled.
+ */
+axs.utils.isElementOrAncestorDisabled = function(element) {
+    if (axs.utils.isElementDisabled(element))
+        return true;
+    var parent = axs.utils.parentElement(element);
+    // fieldset disabled-ness does not flow to descendants of its first legend
+    if (parent && !axs.browserUtils.matchSelector(parent, "fieldset>legend:first-of-type")) {
+        return axs.utils.isElementOrAncestorDisabled(parent);
+    }
```
Comment (alice) [inline src/js/AccessibilityUtils.js]: This should be in our style guide once we have one, but please keep {} consistent between if and else, to avoid confusion.

Comment (alice) [inline src/js/AccessibilityUtils.js]: (actually, the `else` is unnecessary here anyway.)

File: src/js/AccessibilityUtils.js [hunk 3]
```diff
@@ -577,6 +577,40 @@ axs.utils.hasLabel = function(element) {
...
+ * @param {Element} element An element to check.
+ * @return {boolean} True if the element or one of its ancestors is disabled.
+ */
+axs.utils.isElementOrAncestorDisabled = function(element) {
+    if (axs.utils.isElementDisabled(element))
+        return true;
+    var parent = axs.utils.parentElement(element);
+    // fieldset disabled-ness does not flow to descendants of its first legend
+    if (parent && !axs.browserUtils.matchSelector(parent, "fieldset>legend:first-of-type")) {
+        return axs.utils.isElementOrAncestorDisabled(parent);
```
Comment (alice) [inline src/js/AccessibilityUtils.js]: I think this may need a little more subtlety - e.g. a `<span role=button>` inside a `<fieldset disabled>` _won't_ be disabled, right? You'd need to add `aria-disabled` somewhere in the ancestor chain.

Comment (RickSBrown) [inline src/js/AccessibilityUtils.js]: Yeah good point. I'll need to add some unit tests for this... Will update shortly.

File: src/js/AccessibilityUtils.js [hunk 4]
```diff
@@ -577,6 +577,44 @@ axs.utils.hasLabel = function(element) {
...
+axs.utils.isElementDisabled = function(element) {
+    if (axs.browserUtils.matchSelector(element, '[aria-disabled=true], [aria-disabled=true] *')) {
+        return true;
+    }
+    if(!axs.utils.isNativelyDisableable(element) ||
+            axs.browserUtils.matchSelector(element, 'fieldset>legend:first-of-type *')) {
+        return false;
+    }
+    var next = element;
+    do {
```
Comment (alice) [inline src/js/AccessibilityUtils.js]: This is fine, but why not
```for (var next = element; next !== null; next = axs.utils.parentElement(next) { ... }``` ?

Comment (RickSBrown) [inline src/js/AccessibilityUtils.js]: Love it!
I have no excuse for not coming up with that myself :( 

It's not a pattern I have got into the habit of using but it works so elegantly here I'm going to have to review all the JS I have written at work and look for places where I should have done this.

**Comment by alice** [comment]
:+1:
